import { randomUUID } from "crypto";
import { mkdir, readFile, rm, stat, writeFile } from "fs/promises";
import path from "path";

// Storage abstraction for desk file uploads. Swappable backend: the rest of
// the app only ever imports `storage` from this file and calls
// upload/get/delete/list — to move to Vercel Blob (or S3, etc.) later,
// implement the same DeskStorage interface and change the export at the
// bottom of this file. Nothing in app/api/desk-files or the UI needs to change.

export interface StoredFile {
  key: string;
  size: number;
}

export interface DeskStorage {
  upload(buffer: Buffer, originalName: string): Promise<StoredFile>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  list(): Promise<string[]>;
  // A derived, cached variant of an already-uploaded file (right now: a
  // resized photo thumbnail) — same key + suffix on disk, generated lazily
  // on first request and reused after that. `generate` only runs on a
  // cache miss. See lib/desk-services/photo-thumbnail.ts.
  getOrCreateVariant(key: string, variant: string, generate: (original: Buffer) => Promise<Buffer>): Promise<Buffer>;
}

// Files live outside /public — the only way to reach them is through the
// session-checked route handlers in app/api/desk-files, never a direct
// static URL like /public assets would be.
const UPLOAD_ROOT = path.join(process.cwd(), "desk-uploads");

function assertSafeKey(key: string) {
  // Keys are generated by upload() (uuid + extension), never taken verbatim
  // from user input, but this guards against any path-traversal regardless
  // of how get()/delete() end up being called.
  if (key.includes("..") || key.includes("/") || key.includes("\\")) {
    throw new Error("Invalid storage key");
  }
}

class LocalDiskStorage implements DeskStorage {
  private async ensureRoot() {
    await mkdir(UPLOAD_ROOT, { recursive: true });
  }

  async upload(buffer: Buffer, originalName: string): Promise<StoredFile> {
    await this.ensureRoot();
    const ext = path.extname(originalName);
    const key = `${randomUUID()}${ext}`;
    const filePath = path.join(UPLOAD_ROOT, key);
    await writeFile(filePath, buffer);
    return { key, size: buffer.length };
  }

  async get(key: string): Promise<Buffer> {
    assertSafeKey(key);
    return readFile(path.join(UPLOAD_ROOT, key));
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key);
    await rm(path.join(UPLOAD_ROOT, key), { force: true });
    // Best-effort — orphaning a tiny cached thumbnail if this ever grows a
    // second variant name is harmless, so this isn't worth generalizing.
    await rm(path.join(UPLOAD_ROOT, `${key}.thumb`), { force: true });
  }

  async list(): Promise<string[]> {
    await this.ensureRoot();
    const { readdir } = await import("fs/promises");
    return readdir(UPLOAD_ROOT);
  }

  async getOrCreateVariant(key: string, variant: string, generate: (original: Buffer) => Promise<Buffer>): Promise<Buffer> {
    assertSafeKey(key);
    if (variant.includes("..") || variant.includes("/") || variant.includes("\\")) {
      throw new Error("Invalid storage variant");
    }
    await this.ensureRoot();
    const variantPath = path.join(UPLOAD_ROOT, `${key}.${variant}`);
    if (await fileExists(variantPath)) {
      return readFile(variantPath);
    }
    const original = await this.get(key);
    const generated = await generate(original);
    await writeFile(variantPath, generated);
    return generated;
  }
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath);
    return true;
  } catch {
    return false;
  }
}

export { fileExists, UPLOAD_ROOT };

const storage: DeskStorage = new LocalDiskStorage();

export { storage };
